### PR TITLE
Update JVM args a bit.

### PR DESCRIPTION
**Pull request by gburd**

### CODE REVIEW

**Comment by gburd** [comment]
@krestenkrab and @mortengrouleff any of these JVM changes bother you at all?

**Comment by mortengrouleff** [comment]
I don't know what they do, so no...

**Review by mwl — APPROVED** [review]

**Comment by krestenkrab** [comment]
I doubt that `UseStringDeduplication` has a positive impact on Humio. We allocate many many short lived strings in ingest. 

Ideally we should measure these various options and see how they impact the system under load.

**Comment by gburd** [comment]
That’s fair, my understanding of strings in the JVM leads me to believe that this would help somewhat but I’ve not verified my intuition.

**Pull request merged**
